BRANCHES = {
    1: "Afterten",
    2: "Quick Corner",
    3: "Kitchen Warehouse",
    4: "Riverside",
    5: "Nkana East",
    6: "Oxford Two",
    7: "First Class",
    8: "Second Class",
    9: "Oxford One",
    10: "Chimwemwe",
    11: "Matuka",
    12: "ECL",
    13: "Parklands",
    14: "Kalulushi",
    15: "Mufulira",
    16: "Luanshya",
    17: "Bus Station",
    18: "Kansenji",
    19: "Drinks Warehouse",
    20: "Store Room One",
    21: "Cold Room 1 Warehouse",
    22: "Cold Room 2 Warehouse",
    23: "Cold Room 3 Warehouse",
    24: "Cold Room 4 Warehouse",
    25: "Cold Room 5 Warehouse",
    26: "Cold Room 6 Warehouse",
    27: "Cold Room 7 Warehouse",
    28: "Broadway",
    29: "Cloud Test"
}
